# pyre-ignore-all-errors
"""
llm_generator.py — The AI Doctor (Upgraded to 3.3-70B)
=================================================
Week 4: This file takes the search results we got from the FAISS database
and feeds them into an incredibly smart language model (Llama-3.3-70B via Groq).
The model then synthesizes those visual matches into a readable medical report!
"""

import os
import sys
from pathlib import Path

# The Groq library lets us use Llama-3 instantly on the cloud
from groq import Groq

# Setup logging
sys.path.insert(0, str(Path(__file__).resolve().parent))
from utils import get_logger

logger = get_logger(__name__, log_file="logs/llm_generator.log")

def generate_medical_report(user_query, similar_images_metadata, xai_region=None):
    """
    Step 1: Get the API key safely.
    Step 2: Format the FAISS images so the LLM understands them.
    Step 3: Tell Llama-3 to act as an expert Medical AI.
    Step 4: Request the final report.
    """
    
    # 1. Look for the API key in the environment variables
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        logger.error("Wait! You are missing the GROQ_API_KEY environment variable!")
        return "Error: GROQ_API_KEY not found. Please add your free key to the .env file."
        
    client = Groq(api_key=api_key)
    
    # 2. Format the top 5 images making sure we pass the OFFICIAL DIAGNOSIS
    context_text = "\n".join([
        f"- Historical Match {i+1}: Ground-Truth Case Diagnosis: [{img['diagnosis']}]"
        for i, img in enumerate(similar_images_metadata)
    ])
    
    # 3. Build the prompt instructing the LLM on its medical persona
    system_prompt = """
You are a senior board-certified Clinical Radiologist generating a formal diagnostic report for a Chest X-Ray. 
You have been provided with the top matching historical cases retrieved from a FAISS medical vector database, 
each with a verified ground-truth NIH diagnosis label. Your report must be thorough, anatomically precise, 
and evidence-grounded. Use professional radiological terminology throughout.

OPERATIONAL GUIDELINES:
- Use anatomical precision: specify lobes (RUL, RML, RLL, LUL, LLL), zones, and landmarks.
- Link every finding directly to the retrieved RAG evidence.
- Be decisive. Avoid vague language like "may suggest" — use "findings are consistent with."
- Do NOT invent findings not supported by the retrieved context.

GENERATE A COMPLETE RADIOLOGY REPORT IN THE FOLLOWING FORMAT:

**PATIENT STUDY:** Chest X-Ray — PA/AP View

**1. CLINICAL IMPRESSION:**
Provide a 2-3 sentence primary diagnosis statement. Name the condition, describe the typical radiological presentation, and state the confidence level (High/Moderate/Low) based on how consistently the retrieved cases agree.

**2. RADIOLOGICAL FINDINGS:**
Describe what would typically be observed on the X-ray for this diagnosis. Cover:
- Lung fields (any opacities, infiltrates, consolidation, hyperinflation)
- Pleural spaces (effusion, thickening, pneumothorax)
- Cardiac silhouette (size, borders)
- Mediastinum (widening, shift)
- Bony structures (if relevant)
Base these descriptions on the patterns implied by the retrieved diagnosis labels.

**3. DIFFERENTIAL DIAGNOSIS:**
If the retrieved cases show conflicting labels, list up to 2 alternative diagnoses with a brief justification for each. If all retrieved cases agree, state: 'No significant differential — retrieved cases are concordant.'

**4. RAG EVIDENCE ANALYSIS:**
Explain how the retrieved historical ground-truth cases support this conclusion. Mention the diagnosis labels of the matched cases and explain the clinical pattern they represent.

**5. CLINICAL CORRELATION & RECOMMENDATIONS:**
Provide 2-3 specific clinical recommendations, such as:
- Follow-up imaging (CT, lateral view)
- Laboratory investigations
- Urgent vs. routine referral urgency
- Patient monitoring requirements

**6. SEVERITY ASSESSMENT:**
Classify as: ROUTINE | URGENT | EMERGENT
Provide a 1-sentence justification.

**DISCLAIMER:** *This report is generated by an AI-assisted clinical decision support system (Medical RAG-Scanner) and must be reviewed and validated by a board-certified radiologist before any clinical action is taken.*
    """

    xai_context = ""
    if xai_region:
        xai_context = (
            f"\nXAI ACTIVATION ANALYSIS: The Dual Encoder's GradCAM (DenseNet121) and "
            f"Saliency Map (BiomedCLIP ViT) both show maximum activation concentrated "
            f"in the **{xai_region}**. This is a data-driven finding — the AI models "
            f"are focusing on this anatomical region as the primary area of interest. "
            f"Incorporate this specific region into your radiological findings and clinical impression.\n"
        )

    user_prompt = (
        f"Input Query: '{user_query}'\n\n"
        f"RETRIEVED HISTORICAL CASES FROM FAISS VECTOR DATABASE:\n{context_text}\n"
        f"{xai_context}\n"
        "Generate a complete formal radiology report based strictly on the retrieved evidence above."
    )
    
    logger.info("Sending prompt to Groq (Qwen3-32B reasoning model)...")
    
    # 4. Fire the prompt to the cloud and get the response!
    try:
        completion = client.chat.completions.create(
            model="qwen/qwen3-32b",   # Qwen3-32B: active reasoning model on Groq with chain-of-thought
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.3,
            max_tokens=2048,
            stream=False
        )
        raw_report = completion.choices[0].message.content

        # DeepSeek-R1 wraps its internal chain-of-thought in <think>...</think>.
        # Strip it so only the clean clinical report is shown to the user.
        import re
        report = re.sub(r"<think>.*?</think>", "", raw_report, flags=re.DOTALL).strip()

        logger.info("Successfully generated DeepSeek-R1 medical report!")
        return report
        
    except Exception as e:
        logger.error(f"Groq API Error: {str(e)}")
        return f"Error connecting to LLM: {str(e)}"

# ─── This part only runs if you run the file directly in your terminal ───
if __name__ == "__main__":
    # We load the .env file so Python can securely find the API key
    from dotenv import load_dotenv
    load_dotenv() 
    
    print("\n" + "="*50)
    print(" Testing Groq Llama-3.3-70B Connection")
    print("="*50)
    
    # We fake a query and fake some FAISS search results to test the pipeline!
    fake_patient_query = "This patient has a persistent dry cough with some shortness of breath. Is it Pneumonia?"
    fake_database_results = [
        {"diagnosis": "Pneumonia", "similarity": 0.89},
        {"diagnosis": "Infiltration", "similarity": 0.87},
        {"diagnosis": "No Finding", "similarity": 0.45}
    ]
    
    print(f"\n[QUERY SENT]: {fake_patient_query}")
    print("\n[AI DOCTOR OUTPUT]:\n")
    
    # Run the generator!
    final_response = generate_medical_report(fake_patient_query, fake_database_results)
    print(final_response)
    print("\n" + "="*50)
